# Numpy

In [23]:
!pip install numpy

In [3]:
import numpy as np

In [6]:
a = np.array([1,2,3,4])
b = np.array([[5,6,7,8] , [1,2,3,4]])
c = np.array([[[1,2,3,4] , [5,6,7,8]], [[9,0,1,2] , [3,4,5,6]]])


print(a)
print(b)
print(c)

[1 2 3 4]
[[5 6 7 8]
 [1 2 3 4]]
[[[1 2 3 4]
  [5 6 7 8]]

 [[9 0 1 2]
  [3 4 5 6]]]


In [36]:
#creating an array of zeros with 1-D ,2-D , 3-D

a = np.zeros((1,4))

b = np.zeros((3,4))

c = np.zeros((2,3,4))

print(a)
print(b)
print(c)

[[0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [40]:
#creating an array of ones with 1-D, 2-D, 3-D

v = np.ones((1,4))

d = np.ones((4,4))

g = np.ones((2,4,4))

print(v)
print(d)
print(g)

[[1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [50]:
#create an array of evenly spaced values (step values)


d = np.arange(10,30,3) #n-1

c = np.arange(1,50,2)

print(d)
print(c)

[10 13 16 19 22 25 28]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [56]:
#create an array of evenly spaced values (number of samples)

t = np.linspace(2,10,5)

b = np.linspace(10,20,3)

print(t)
print(b)

[ 2.  4.  6.  8. 10.]
[10. 15. 20.]


In [78]:
#create an constant array
#with 1-D , 2-D , 3-D array

a = np.full([4],7)   #1-D

b= np.full((4,4),8)

c = np.full((2,4,4),9)

print(a)
print(a.ndim)
print(b)
print(b.ndim)
print(c)
print(c.ndim)

[7 7 7 7]
1
[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
2
[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]
3


In [94]:
#create a marix with identity matrix

a = np.eye(6)
print(a)



[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [120]:
#create a random array

a = np.random.random((4))
b = np.random.random((4,4))
c = np.random.random((2,4,4))

print(a)
print(b)
print(c)

[0.05690538 0.33428934 0.91804835 0.9178712 ]
[[0.81797071 0.71016125 0.36400551 0.84334465]
 [0.43255218 0.19833043 0.44497119 0.0172557 ]
 [0.93228416 0.40939995 0.52162559 0.2076326 ]
 [0.68930438 0.84659003 0.21784413 0.63946968]]
[[[0.96578297 0.12743439 0.09017688 0.85439819]
  [0.68441586 0.24931283 0.45356251 0.95432113]
  [0.2396587  0.79889831 0.16630143 0.33460975]
  [0.88304807 0.74181602 0.03445796 0.13576133]]

 [[0.7201654  0.28397976 0.57840114 0.78925155]
  [0.18101437 0.38673476 0.59771686 0.63953631]
  [0.09194331 0.89074767 0.75029    0.1055436 ]
  [0.64262679 0.76886508 0.27263506 0.78934373]]]


In [140]:
# random integer in b/w two values

a = np.random.randint(1,10)
print(a)

8


In [154]:
#find shape of an array

a = np.array([1,2,3,4])

b = np.array([[1,2,3,4],
              [5,6,7,8]])

c = np.array([[[1,2,3,4],
              [5,6,7,8],
              [7,8,9,0]]])

print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 4)
(1, 3, 4)


In [158]:
#find size of an array

a = np.array([1,2,3,34])

b = np.array([[1,2,3,4] , [6,7,8,9]])

print(a.size)
print(b.size)

4
8


In [172]:
#length of an array 

a = np.array([[1,2,3,4],
              [3,4,5,6],
              [6,7,8,9],
              [8,9,0,1],
              [4,5,6,7]])

b = np.array([1,2,3,4,56,])

print(len(a))
print(len(b))

5
5


# Access array  elements

In [188]:
#indexing of an array 

arr = np.array(('v','a','s','u'))

arr1 = np.array((1,2,3,4,5,6,7,8,9))

print(arr[3])
print(arr1[4])

arr2 = "vsundhar"
np.array
print(arr2[3])

u
5
n


In [190]:
#adding of elements in array by using index

arr = np.array([1,2,3,4,5,6,7])

print(arr[2] + arr[4] + arr[6])

15


In [9]:
#access 2-D array

arr = np.array([[1,2,3,4,5],
              [4,5,6,7,8],
              [3,4,5,6,7],
              [7,8,9,0,1],
              [5,6,7,8,9]])



print("3rd element of 2nd row: ", arr[2,3]) 
print("4rd element of 4nd row: ", arr[4,4])

3rd element of 2nd row:  6
4rd element of 4nd row:  9


In [13]:
#access 3-D array

arr = np.array([[[1,2,3,4],[5,6,7,8]],
              [[3,4,5,6],[2,3,4,5]],
              [[6,7,8,9],[7,6,5,4]],
              [[7,8,9,0],[1,2,3,4]]])

print(arr[3,1,2])
print(arr[2,0,1])

3
7


# Data types



#data types in numpy
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
tring
'''


In [7]:
#1.string

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [13]:
#2.integer

arr=np.array([1,2,3,4,66611111,4444],dtype='i')
print(arr)
print(arr.dtype)

[       1        2        3        4 66611111     4444]
int32


In [44]:
#changing float to int

arr=np.array([1.1,2.2,3.3,4,5.5])
new_arr=arr.astype('i')
print(new_arr)
print(new_arr.dtype)

[1 2 3 4 5]
int32


In [40]:
##changing float to boolean

arr=np.array([0.0,1.1,2.2,3.3,4,5.5])
new_arr = arr.astype(bool)
print(new_arr)
print(new_arr.dtype)

[False  True  True  True  True  True]
bool


In [42]:
#changing int to float

arr=np.array([0,9,8,7,6,5,])
new_arr = arr.astype('f')
print(new_arr)
print(new_arr.dtype)

[0. 9. 8. 7. 6. 5.]
float32


In [28]:
#changing float to unsigned integer

arr=np.array([1.1,2.2,3.3,4,5.5])
new_arr=arr.astype('U')
print(new_arr)
print(new_arr.dtype)

['1.1' '2.2' '3.3' '4.0' '5.5']
<U32


In [46]:
##changing int to unsigned integer

arr=np.array([1,2,3,4,5])
new_arr=arr.astype('U')
print(new_arr)
print(new_arr.dtype)

['1' '2' '3' '4' '5']
<U11


In [48]:
#changing float to complex float

arr=np.array([1.1,2.2,3.3,4,5.5])
new_arr=arr.astype('c')
print(new_arr)
print(new_arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [50]:
#changing int to complex float

arr=np.array([1,2,3,4,5])
new_arr=arr.astype('c')
print(new_arr)
print(new_arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [56]:
#copy method

arr=np.array([10,4,5,30,60,70,33,444])
x = arr.copy()
arr[0]=222
print(arr)
print(x)

[222   4   5  30  60  70  33 444]
[ 10   4   5  30  60  70  33 444]


In [58]:
#view method

arr=np.array([10,4,5,30,60,70,33,444])
temp=arr.view()
arr[0]=2
print(temp)

[  2   4   5  30  60  70  33 444]


In [60]:
#shape

arr = np.array([[2,3,4,5],
              [6,7,8,9]])

print(arr.shape)


(2, 4)


In [9]:
#Reshaping arrays
#converting 1D array to 2D array

arr= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
x=arr.reshape(2,7)

print(x)

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
x=arr.reshape(3,6)
y=arr.reshape(9,2)

print(x)
print(y)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]]


In [17]:
##converting 1D array into 3D array

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
x=arr.reshape(2,2,5)
print(x)
print("++++++++++++++++++++++++++")
y=arr.reshape(5,2,2)
print(y)


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
++++++++++++++++++++++++++
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


In [21]:
##converting 2D array into 1D array

arr=np.array([[1,2,3,4,5,6],
              [7,8,9,10,11,12],
              [13,14,15,16,17,18]])
x=arr.reshape(arr.size)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [29]:
##converting 2D array into 3D array

arr=np.array([[1,2,3,4,5,6],
              [7,8,9,10,11,12],
              [13,14,15,16,17,18]])
print(arr.size)
x=arr.reshape(3,2,3)
print(x)
print("++++++++++++++++++++++")
y=arr.reshape(2,3,3)
print(y)


18
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
++++++++++++++++++++++
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [5]:
#converting 3D array into 1D array

arr=np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]],
              [[13,14,15,16,17,18],[19,20,21,22,23,24]],
              [[25,26,27,28,29,30],[31,32,33,34,35,36]]])
x=arr.reshape(arr.size)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [7]:
#converting 3D array into 2D array

arr=np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]],
              [[13,14,15,16,17,18],[19,20,21,22,23,24]],
              [[25,26,27,28,29,30],[31,32,33,34,35,36]]])
print(arr.size)
x=arr.reshape(6,6)
print(x)
print("---------------------------------------------------")
y=arr.reshape(2,18)
print(y)


36
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
---------------------------------------------------
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36]]


In [9]:
##sorting arrays

arr=np.array([6,8,30,79,45,66,670])
x=np.sort(arr)
print(x)

[  6   8  30  45  66  79 670]


In [13]:
##slicing arrays

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
#positive slicing
print(arr[1:9])
#negative slicing
print(arr[-11:-2])

[2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18]


In [17]:
##slicing 2D arrays

arr=np.array([[1,2,3,4,5,6],
              [7,8,9,10,11,12],
              [13,14,15,16,17,18]])
print(arr[0,1:4])
print(arr[0:2,3:5])


[2 3 4]
[[ 4  5]
 [10 11]]
